project:
  type: website

website:
  title: "Adam D McKinnon"
  site-url: "https://www.adam-d-mckinnon.com/"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/adamdmckinnon/
      - icon: github
        href: https://github.com/adam-d-mckinnon
        
format:
  html:
    theme: lux
    css: theme.scss
    code-fold: true
    toc-depth: 3

editor: visual

