{
  "hash": "a8c009376f00357cd0b2e41004226740",
  "result": {
    "markdown": "---\ntitle: 'Measuring Impact in HR: A Practical Demonstration'\ndate: 06-06-2021\ndescription: \"A 'How To' article on the measurment of differences between groups in HR settings.\"\nauthor: \n    - name: Adam D McKinnon\n    - name: Sambit Das\ncategories: [Impact Measurement, t-test, rstatix, ggpubr, Plotly, R]\nimage: \"patricia-serna-zPZ9vqqDNBA-unsplash.jpg\"\ntitle-block-banner: true\n---\n\n::: {.cell}\n::: {.cell-output-display}\n![Photo by [patricia serna](https://unsplash.com/@sernarial) on [Unsplash](https://unsplash.com/).](patricia-serna-zPZ9vqqDNBA-unsplash.jpg){width=100%}\n:::\n:::\n\n\n# Differences in Training Outcomes\n\nThe decision we are trying to inform here is: **in which training format should we invest?**\n\nThe context is simple. The organisation has introduced a new digital (i.e., online e-training) for new starters. The new digital training takes half a day to complete. The traditional model of training delivery was a full-day of face-to-face activity.\n\nThe company wants to understand which training format to commit to in future. Enter People Analytics Team!\n\n<br>\n\n# Workflow\n\nThe workflow is as follows:\n\n1.  **INGEST:** We began by ingesting the end-of-course assessment data from the training (previously collected). The data was from a random selection of participants that have completed the training in one of the training formats (i.e., face-to-face or digital).\n\n2.  **ANALYSE:** From there we analysed the end-of-course assessment results. This was done using some basic descriptive statistics and a simple Independent Samples t-test. Prior to performing the t-test we completed an assessment of the t-test assumptions.\n\n3.  **VISUALISE:** We visualised the results obtained from the two training formats to make it easier for our audience to interpret and understand,\n\n4.  **QUANTIFY:** Finally, we quantified the benefits of the optimal approach.\n\nThe R code for this analysis is presented below, following the workflow steps above. In addition, some guidance regarding the steps and interpretation of the outcomes are provided. We have used namepsacing throughout to illustrate which packages are being used for any given function call. While this helps to ensure the accuracy of our code, it also facilitates learning and ease of understanding for fellow practitioners.\n\n<br>\n\n## 1. Ingesting Data\n\nThe first code chunk is fairly simple. We load our packages, read in our assessment results, clean the variable names, and finally take a simple look at the structure of the data to see what we are working with.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the packages we will use for this workflow\nlibrary(tidyverse) # workhorse\nlibrary(readxl) # ingesting our data\nlibrary(janitor) # cleaning variable names\nlibrary(rstatix) # performing t-tests\nlibrary(ggpubr) # simple boxplots\n\n\n# Ingest our training assessment results\nassessment_results_tbl <- readxl::read_excel(path = \"training_data.xlsx\") %>% \n                          janitor::clean_names()\n\n\n# Get a feel for the data and its structure\ndplyr::glimpse(assessment_results_tbl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 27\nColumns: 2\n$ training <chr> \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"…\n$ result   <dbl> 56, 50, 52, 44, 52, 47, 47, 53, 45, 48, 42, 51, 42, 43, 44, 5…\n```\n:::\n:::\n\n\nA key point to note is that in the **\"training\"** variable a response of \"A\" equates to the traditional face-to-face delivery mode, while \"B\" equates to the new digital learning format.\n\n<br>\n\n## 2. Analysing Data\n\nThe analysis comprised the following steps:\n\n1.  Firstly, we performed a quick exploration of the data by getting some summary statistics.\n\n2.  Secondly, we performed our t-test to determine if statistically significant differences existed in assessment outcome scores achieved by the two training formats.\n\nThese two steps are performed sequentially.\n\n### Step 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2a. get some summary stats\ndescriptive_stats_tbl <- assessment_results_tbl %>% \n  dplyr::group_by(training) %>% \n  rstatix::get_summary_stats(result, type = \"mean_sd\")\n\n\ndescriptive_stats_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  training variable     n  mean    sd\n  <chr>    <chr>    <dbl> <dbl> <dbl>\n1 A        result      15  47.7  4.42\n2 B        result      12  56.5  4.28\n```\n:::\n:::\n\n\n### Interpretation\n\nOur descriptive statistics indicate an interesting outcome. It appears a notable difference exists between training formats in the mean score achieved on the assessment outcome, Training B (digital) seems to achieve on average a higher score (56.5) than Training A (face-to-face). However, the question remains--is this difference statistically significant?\n\n<br>\n\n### Step 2.\n\nBefore we can perform the t-test we must check several assumptions to ensure a t-test is appropriate. The assumptions are as follows:\n\n| **Assumption**                                                                | **Outcome**                                                                                                                                                       |\n|------------------------------------|------------------------------------|\n| 1\\. The data are continuous (not discrete).                                   | Our assessment outcomes scores are continuous - [**CHECK**]{.underline}                                                                                           |\n| 2\\. The data follow the normal probability distribution.                      | We will test for normality using a Q-Q plot (Quantile-Quantile plot) and the Shapiro-Wilk's test.                                                                 |\n| 3\\. The variances of the two populations are equal.                           | We will test for equal variance using the Levene Test.                                                                                                            |\n| 4\\. The two samples are independent.                                          | Our training participants could only participate in one type of training (i.e., face-to-face or digital) so our samples are independent - [**CHECK**]{.underline} |\n| 5\\. Both samples are simple random samples from their respective populations. | Our participant results were randomly selected for analysis - [**CHECK!**]{.underline}                                                                            |\n\nIf the data is normally distributed and the variance across the two groups (e.g. Training Groups A & B) are equal then a t-test can be used effectively. Let's check the last two assumptions and then analyse the data!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2b. Normality Tests\nggpubr::ggqqplot(assessment_results_tbl$result,\n                 title = \"Normality Assessment\") %>% \n  plotly::plotly_build()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-d16bb3f2b389b2d2ff4a\" style=\"width:100%;height:464px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d16bb3f2b389b2d2ff4a\">{\"x\":{\"data\":[{\"x\":[-2.08535556603183,-1.59321881802305,-1.32495768889298,-1.12814364527876,-0.967421566101701,-0.828464648581135,-0.703921788828513,-0.589455797849779,-0.482248214837923,-0.380325641763631,-0.282216147062508,-0.186756121063737,-0.0929718485610738,0,0.0929718485610739,0.186756121063737,0.282216147062508,0.380325641763631,0.482248214837923,0.589455797849779,0.703921788828513,0.828464648581135,0.967421566101701,1.12814364527876,1.32495768889298,1.59321881802305,2.08535556603183],\"y\":[42,42,43,44,44,45,47,47,48,50,51,52,52,52,53,53,53,53,54,55,56,56,57,57,59,64,65],\"text\":[\"theoretical: -2.08535557<br />sample: 42<br />x: 42\",\"theoretical: -1.59321882<br />sample: 42<br />x: 42\",\"theoretical: -1.32495769<br />sample: 43<br />x: 43\",\"theoretical: -1.12814365<br />sample: 44<br />x: 44\",\"theoretical: -0.96742157<br />sample: 44<br />x: 44\",\"theoretical: -0.82846465<br />sample: 45<br />x: 45\",\"theoretical: -0.70392179<br />sample: 47<br />x: 47\",\"theoretical: -0.58945580<br />sample: 47<br />x: 47\",\"theoretical: -0.48224821<br />sample: 48<br />x: 48\",\"theoretical: -0.38032564<br />sample: 50<br />x: 50\",\"theoretical: -0.28221615<br />sample: 51<br />x: 51\",\"theoretical: -0.18675612<br />sample: 52<br />x: 52\",\"theoretical: -0.09297185<br />sample: 52<br />x: 52\",\"theoretical:  0.00000000<br />sample: 52<br />x: 52\",\"theoretical:  0.09297185<br />sample: 53<br />x: 53\",\"theoretical:  0.18675612<br />sample: 53<br />x: 53\",\"theoretical:  0.28221615<br />sample: 53<br />x: 53\",\"theoretical:  0.38032564<br />sample: 53<br />x: 53\",\"theoretical:  0.48224821<br />sample: 54<br />x: 54\",\"theoretical:  0.58945580<br />sample: 55<br />x: 55\",\"theoretical:  0.70392179<br />sample: 56<br />x: 56\",\"theoretical:  0.82846465<br />sample: 56<br />x: 56\",\"theoretical:  0.96742157<br />sample: 57<br />x: 57\",\"theoretical:  1.12814365<br />sample: 57<br />x: 57\",\"theoretical:  1.32495769<br />sample: 59<br />x: 59\",\"theoretical:  1.59321882<br />sample: 64<br />x: 64\",\"theoretical:  2.08535557<br />sample: 65<br />x: 65\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,0,0,1)\",\"opacity\":1,\"size\":5.66929133858268,\"symbol\":\"circle\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,0,0,1)\"}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-2.08535556603183,-1.59321881802305,-1.32495768889298,-1.12814364527876,-0.967421566101701,-0.828464648581135,-0.703921788828513,-0.589455797849779,-0.482248214837923,-0.380325641763631,-0.282216147062508,-0.186756121063737,-0.0929718485610738,0,0.0929718485610739,0.186756121063737,0.282216147062508,0.380325641763631,0.482248214837923,0.589455797849779,0.703921788828513,0.828464648581135,0.967421566101701,1.12814364527876,1.32495768889298,1.59321881802305,2.08535556603183],\"y\":[38.1100506485699,41.2110335447951,42.9013628618402,44.141499847046,45.1542192194367,46.0297950147556,46.8145469754708,47.5358039871869,48.2113253389465,48.8535455290084,49.4717392856348,50.0732385825135,50.6641788570253,51.25,51.8358211429747,52.4267614174865,53.0282607143652,53.6464544709916,54.2886746610536,54.9641960128131,55.6854530245292,56.4702049852444,57.3457807805633,58.358500152954,59.5986371381598,61.2889664552049,64.3899493514301],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[-2.08535556603183,-1.59321881802305,-1.32495768889298,-1.12814364527876,-0.967421566101701,-0.828464648581135,-0.703921788828513,-0.589455797849779,-0.482248214837923,-0.380325641763631,-0.282216147062508,-0.186756121063737,-0.0929718485610738,0,0.0929718485610739,0.186756121063737,0.282216147062508,0.380325641763631,0.482248214837923,0.589455797849779,0.703921788828513,0.828464648581135,0.967421566101701,1.12814364527876,1.32495768889298,1.59321881802305,2.08535556603183,2.08535556603183,2.08535556603183,1.59321881802305,1.32495768889298,1.12814364527876,0.967421566101701,0.828464648581135,0.703921788828513,0.589455797849779,0.482248214837923,0.380325641763631,0.282216147062508,0.186756121063737,0.0929718485610739,0,-0.0929718485610738,-0.186756121063737,-0.282216147062508,-0.380325641763631,-0.482248214837923,-0.589455797849779,-0.703921788828513,-0.828464648581135,-0.967421566101701,-1.12814364527876,-1.32495768889298,-1.59321881802305,-2.08535556603183,-2.08535556603183],\"y\":[31.0448613531787,36.3557281847318,38.7473888138278,40.3602188074258,41.6090860991283,42.6480073477773,43.5513950111512,44.3610983147921,45.1031767723232,45.79512917315,46.4494399520156,47.075495893053,47.6807070934095,48.2712111253076,48.8523493793589,49.4290187280261,50.0059613807459,50.5880381151333,51.1805260944303,51.7894903404182,52.4223010602096,53.0884173182661,53.800647660255,54.5772191133338,55.4446630901475,56.4336610951415,57.324760056039,57.324760056039,71.4551386468213,66.1442718152682,63.7526111861722,62.1397811925742,60.8909139008717,59.8519926522227,58.9486049888488,58.1389016852079,57.3968232276768,56.70487082685,56.0505600479844,55.424504106947,54.8192929065905,54.2287888746924,53.6476506206411,53.0709812719739,52.4940386192541,51.9119618848667,51.3194739055697,50.7105096595818,50.0776989397904,49.4115826817339,48.699352339745,47.9227808866662,47.0553369098525,46.0663389048585,45.175239943961,31.0448613531787],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\",\"dash\":\"solid\"},\"fill\":\"toself\",\"fillcolor\":\"rgba(0,0,0,0.2)\",\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":46.2864259028643,\"r\":7.97011207970112,\"b\":47.0236612702366,\"l\":43.8356164383562},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022},\"title\":{\"text\":\"Normality Assessment\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":19.1282689912827},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-2.29389112263501,2.29389112263501],\"tickmode\":\"array\",\"ticktext\":[\"-2\",\"-1\",\"0\",\"1\",\"2\"],\"tickvals\":[-2,-1,0,1,2],\"categoryorder\":\"array\",\"categoryarray\":[\"-2\",\"-1\",\"0\",\"1\",\"2\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(0,0,0,1)\",\"ticklen\":3.98505603985056,\"tickwidth\":0.724555643609193,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Theoretical\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[29.0243474884966,73.4756525115034],\"tickmode\":\"array\",\"ticktext\":[\"30\",\"40\",\"50\",\"60\",\"70\"],\"tickvals\":[30,40,50,60,70],\"categoryorder\":\"array\",\"categoryarray\":[\"30\",\"40\",\"50\",\"60\",\"70\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(0,0,0,1)\",\"ticklen\":3.98505603985056,\"tickwidth\":0.724555643609193,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Sample\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":2.06156048675734,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"14269191b4c79\":{\"sample\":{},\"type\":\"scatter\"},\"142694f39a8cf\":{\"sample\":{}},\"142695279d6ab\":{\"sample\":{}}},\"cur_data\":\"14269191b4c79\",\"visdat\":{\"14269191b4c79\":[\"function (y) \",\"x\"],\"142694f39a8cf\":[\"function (y) \",\"x\"],\"142695279d6ab\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n\n```{.r .cell-code}\nrstatix::shapiro_test(assessment_results_tbl$result)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 3\n  variable                      statistic p.value\n  <chr>                             <dbl>   <dbl>\n1 assessment_results_tbl$result     0.958   0.338\n```\n:::\n\n```{.r .cell-code}\n# 2c. Equal Variance - levene's test\nlevene_test(result ~ training, data = assessment_results_tbl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n    df1   df2 statistic     p\n  <int> <int>     <dbl> <dbl>\n1     1    25     0.242 0.627\n```\n:::\n\n```{.r .cell-code}\n# 2d. perform the t-test\n(t_test_tbl <- assessment_results_tbl %>% \n  rstatix::t_test(formula = result ~ training, var.equal = TRUE) %>% \n  rstatix::add_significance())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 9\n  .y.    group1 group2    n1    n2 statistic    df         p p.signif\n  <chr>  <chr>  <chr>  <int> <int>     <dbl> <dbl>     <dbl> <chr>   \n1 result A      B         15    12     -5.20    25 0.0000223 ****    \n```\n:::\n:::\n\n\n<br>\n\n### Interpretation\n\n**Normality** Our QQ plot suggests that we can assume normality. The distribution of results are falling approximately along the reference line and within the bounds. However, the QQ plot can be sensitive to small sample sizes. To further validate normality we performed the Shapiro Wilk's test. This test again suggests that the data are normally distributed, as the p-value (0.338) is greater than 0.05. We can assume normality!\n\n**Equal Variance** We use the levene's test to determine whether both the training methods have an approximately equal variance. Since our p-value (0.627) is greater than 0.05 we can assume that the variance in outcome assessments scores is not statistically significantly different for the two training methods. We can assume equal variance! All our assumptions are met and we can perform the t-test.\n\n**t-test** The t-test indicates that the difference is highly significant (p-value = 0.0002); well below a cut-off of 0.01. This difference is extremely unlikely to be by chance alone and suggests that the digital training yields a better outcome, at least as defined by the assessment outcomes.\n\n<br>\n\n## 3. Visualising Results\n\nOur next step is to visualise the differences achieved by the two training formats. The intent here is to ensure our stakeholders can clearly appreciate that a notable difference exists, and subsequently take an investment decision with confidence. To illustrate the difference observed, we opted to use a Box-Plot, which displays the distribution of scores in each group, coupled with some descriptive statistics. As with our QQ plot, we have used the Plotly package to make the plot interactive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 3. visualise the results from the two training methods\n\ntraining_plot <- assessment_results_tbl %>%  \n                 ggpubr::ggboxplot(x     = \"training\", \n                                   y     = \"result\",\n                                   fill  = \"training\",\n                                   xlab  = \"Training Delivery Format\",\n                                   ylab  = \"Assessment Result\") \nt <- list(\n  family = \"arial\",\n  size = 12)\n\n\n# make the graph interactive\nplotly::plotly_build(training_plot) %>% \n  plotly::layout(title = \"<b>Difference in Assessment Results by Training Delivery Format</b>\",\n                 font = t,\n                 showlegend = FALSE) \n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-17ade52e18c808896047\" style=\"width:100%;height:464px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-17ade52e18c808896047\">{\"x\":{\"data\":[{\"x\":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],\"y\":[56,50,52,44,52,47,47,53,45,48,42,51,42,43,44],\"hoverinfo\":\"y\",\"type\":\"box\",\"fillcolor\":\"rgba(248,118,109,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.66929133858268},\"line\":{\"color\":\"rgba(0,0,0,1)\",\"width\":1.88976377952756},\"name\":\"A\",\"legendgroup\":\"A\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[2,2,2,2,2,2,2,2,2,2,2,2],\"y\":[59,54,55,65,52,57,64,53,53,56,53,57],\"hoverinfo\":\"y\",\"type\":\"box\",\"fillcolor\":\"rgba(0,191,196,1)\",\"marker\":{\"opacity\":null,\"outliercolor\":\"rgba(0,0,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,0,0,1)\"},\"size\":5.66929133858268},\"line\":{\"color\":\"rgba(0,0,0,1)\",\"width\":1.88976377952756},\"name\":\"B\",\"legendgroup\":\"B\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":27.1581569115816,\"r\":7.97011207970112,\"b\":47.0236612702366,\"l\":43.8356164383562},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"arial\",\"size\":12},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.4,2.6],\"tickmode\":\"array\",\"ticktext\":[\"A\",\"B\"],\"tickvals\":[1,2],\"categoryorder\":\"array\",\"categoryarray\":[\"A\",\"B\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(0,0,0,1)\",\"ticklen\":3.98505603985056,\"tickwidth\":0.724555643609193,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Training Delivery Format\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[40.85,66.15],\"tickmode\":\"array\",\"ticktext\":[\"45\",\"50\",\"55\",\"60\",\"65\"],\"tickvals\":[45,50,55,60,65],\"categoryorder\":\"array\",\"categoryarray\":[\"45\",\"50\",\"55\",\"60\",\"65\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(0,0,0,1)\",\"ticklen\":3.98505603985056,\"tickwidth\":0.724555643609193,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Assessment Result\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":2.06156048675734,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":12.7521793275218},\"title\":{\"text\":\"training\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":15.9402241594022}}},\"hovermode\":\"closest\",\"barmode\":\"relative\",\"title\":\"<b>Difference in Assessment Results by Training Delivery Format<\\/b>\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"1426968c81973\":{\"x\":{},\"y\":{},\"fill\":{},\"type\":\"box\"}},\"cur_data\":\"1426968c81973\",\"visdat\":{\"1426968c81973\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\n<br>\n\n### Interpretation\n\nOur visualisation seeks to clearly illustrate that employees who completed the digital training performed better on the end-of-course assessment. This may suggest that the digital training results in better knowledge retention (i.e., they are learning more).\n\nThe line crossing each box on the boxplot indicates the median score of each training format. The median is the middle value achieved on the assessment results for each training format. There is a clear difference between the two groups when comparing these lines. This is worth calling out when delivering the results to stakeholders.\n\n<br>\n\n## 4. Quantifying Benefit\n\nThere are two key ways in which we can further quantify the differences of the training formats:\n\n1.  The percentage change in performance. We have identified the gain is statistically significant and visualised the difference above. We can make this increase in performance more accessible to a broader audience by indicating the performance gain as a percentage.<br>\n\n2.  The cost difference of the delivery formats. By calculating the cost difference of delivering the training over a year or more for the two formats.\n\nOn the basis of these two metrics we are in a better position to recommend a future course of action.\n\n**Performance Efficiency**\n\nUsing the mean score from each training group we can calculate the % gain in performance. The code is presented in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 4. quantify the benefit  \n# mean assessment score for f2f training\ntrain_A_mean <- descriptive_stats_tbl %>% \n  dplyr::filter(training == \"A\") %>% \n  pull(mean)\n\n\n# mean assessment score for digital training\ntrain_B_mean <- descriptive_stats_tbl %>% \n  dplyr::filter(training == \"B\") %>% \n  pull(mean)\n\n\n# calculate % increase in performance\n(pct_increase = ((train_B_mean - train_A_mean)/ train_A_mean) %>% scales::percent())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"18%\"\n```\n:::\n:::\n\n\n**Cost Efficiency**\n\nBelow is an except from an excel spreadsheet in which we have detailed costs associated with both training formats.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"training_costs_3.png\")\n```\n\n::: {.cell-output-display}\n![Cost of training offerings.](training_costs_3.png){width=100%}\n:::\n:::\n\n\n<br>\n\n### Interpretation\n\nOur performance gains are straightforward--digital training results in end of course assessment scores that are 18% higher than traditional face-to-face delivery. This kind of result is accessible to all audiences, and is compelling! In addition, we are confident that the result is a function of the training delivery format based on the results of our t-test.\n\nOur simple cost assessment also creates a compelling picture of the financial savings associated with digital training. In one year we stand to create **\\$8,400 in savings** if we move to a digital format, and this increases to **\\$21,800** at the end of two years.\n\n<br>\n\n# Recommendation\n\nOur recommendation is to invest in the Digital Training! Our rationale:\n\n1.  **Digital training is more effective!** Digital training yields 18% better performance outcomes on the end of course assessment. This result is statistically significant, and more importantly practically significant, as it better sets up our new starters for success!\n\n<br>\n\n2.  **Digital training is cheaper!** Digital training costs \\$21,800 less than face-to-face training over a 2 year period. In addition, in each year we have an indirect benefit of giving 110 employees a half day back to invest in other activities!\n\n<br>\n\n3.  **Digital training is more scaleable!** Digital training can support an unlimited number of participants should recruitment numbers increase for any reason. The ability to accommodate increased numbers of participants also has cost implications (i.e., face-to-face becomes more expensive), further reinforcing the cost benefit of the digital training approach.\n\n<br>\n\n4.  **Digital training is more flexible!** Digital training is not limited by pandemic conditions, and affords employees with more flexibility, a message worth reinforcing early in the careers of new starters!\n\n<br>\n\nFurther time could be invested to speak with employees that recently completed the two training formats to validate the results identified and the recommendation provided.\n\n<br>\n\n# Conclusion\n\nThe above case study provides a simple example of using People Analytics to inform a HR investment decision. We used R to analyse training results, determine whether statistically significant differences existed in outcome scores, visualised the results and then quantified the benefit of the respective training modes. Collectively, the analytic evidence suggested a clear investment decision, which could be augmented with user experience feedback. **Happy measuring!**\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.5.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.1/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}